DROP TABLE IF EXISTS submissions;
CREATE TABLE IF NOT EXISTS submissions (
  id TEXT PRIMARY KEY,
  created_at TEXT NOT NULL,
  weight_value TEXT,
  weight_label TEXT,
  back_condition TEXT,
  firmness TEXT,
  override_er REAL,
  tolerance REAL,
  top_layer_min REAL,
  bottom_layer_min REAL,
  width_in REAL,
  height_in REAL,
  mattress_thickness_in REAL,
  selected_option_key TEXT,
  selected_option_label TEXT,
  target_er REAL,
  actual_er REAL,
  delta_er REAL,
  total_thickness REAL,
  er_depth REAL,
  estimated_price REAL,
  status_text TEXT,
  calc_version TEXT,
  app_version TEXT,
  generated_options_json TEXT NOT NULL,
  layers_json TEXT NOT NULL,
  payload_json TEXT NOT NULL,
  user_agent TEXT
);
